1. On-time Delivery:

AVG(
  CASE 
    WHEN "_APX_WDCRP_CASES"."PROMISED_DATE" >= "_APX_WDCRP_CASES"."DELIVERED_DATE" 
    THEN 1.0 
    ELSE 0.0 
  END
)

2. Early Delivery:
AVG(
  CASE 
    WHEN "_APX_WDCRP_CASES"."DELIVERED_DATE" < "_APX_WDCRP_CASES"."PROMISED_DATE" 
    THEN 1.0 
    ELSE 0.0 
  END
)

3. Late Delivery :
AVG(
  CASE 
    WHEN "_APX_WDCRP_CASES"."DELIVERED_DATE" > "_APX_WDCRP_CASES"."PROMISED_DATE" 
    THEN 1.0 
    ELSE 0.0 
  END
)
  
4.  Rework Rate :
SUM(CASE WHEN PU_COUNT("_APX_WDCRP_CASES","_APX_WDCRP_ACTIVITIES"."ACTIVITY_EN","_APX_WDCRP_ACTIVITIES"."ACTIVITY_EN" 
IN (<%=reworkActivities%>)) > 1 THEN 1.0 ELSE 0.0 END) / COUNT_TABLE("_APX_WDCRP_CASES")

5. Late Delivery fee :
SUM(
  CASE 
    WHEN "_APX_WDCRP_CASES"."DELIVERED_DATE" > "_APX_WDCRP_CASES"."PROMISED_DATE" 
    THEN "_APX_WDCRP_CASES"."DELIVERED_QUANTITY" * 0.75 
    ELSE 0 
  END
)

6.  Deadline conformance:
AVG(
  CASE
    WHEN "_APX_WDCRP_CASES"."DELIVERED_DATE" <= "_APX_WDCRP_CASES"."PROMISED_DATE" THEN 1.0
    ELSE 0.0
  END
)

7. Volume Conformance :
AVG(
  CASE
    WHEN "_APX_WDCRP_CASES"."ORDERED_QUANTITY" <= "_APX_WDCRP_CASES"."DELIVERED_QUANTITY" THEN 1.0
    ELSE 0.0
  END
)

8. Loss Ratio :
(
  AVG(
    CASE 
      WHEN "_APX_WDCRP_CASES"."DELIVERED_DATE" > "_APX_WDCRP_CASES"."PROMISED_DATE"
      THEN "_APX_WDCRP_CASES"."DELIVERED_QUANTITY" * 0.75
      ELSE 0
    END
  )
  /
  AVG("_APX_WDCRP_CASES"."ORDER_VALUE")
)

9. Non Automation :
AVG(CASE WHEN "_APX_WDCRP_CASES"."WAREHOUSE_TYPE" = 'Non-automated' THEN 1.0 ELSE 0.0 END)

10. Avg throughput time :
AVG(CALC_THROUGHPUT(ALL_OCCURRENCE['Process Start'] TO ALL_OCCURRENCE['Process End'], REMAP_TIMESTAMPS("_APX_WDCRP_ACTIVITIES"."EVENTTIME", DAYS)))

11. Avg time to ship goods in hours:
AVG (
  CALC_THROUGHPUT (  FIRST_OCCURRENCE [ 'Load shipment' ] TO LAST_OCCURRENCE [ 'Goods delivered' ] , REMAP_TIMESTAMPS ("_APX_WDCRP_ACTIVITIES"."EVENTTIME" , MINUTES) ) / 60
)

12. Eventtime in quaters :
CONCAT(
  YEAR(ROUND_YEAR("_APX_WDCRP_ACTIVITIES"."EVENTTIME")),
  '-',
  CASE
    WHEN MONTH("_APX_WDCRP_ACTIVITIES"."EVENTTIME") BETWEEN 1 AND 3 THEN 'Q1'
    WHEN MONTH("_APX_WDCRP_ACTIVITIES"."EVENTTIME") BETWEEN 4 AND 6 THEN 'Q2'
    WHEN MONTH("_APX_WDCRP_ACTIVITIES"."EVENTTIME") BETWEEN 7 AND 9 THEN 'Q3'
    WHEN MONTH("_APX_WDCRP_ACTIVITIES"."EVENTTIME") BETWEEN 10 AND 12 THEN 'Q4'
  END
)

13. Net Order Value:
SUM("_APX_WDCRP_CASES"."ORDER_VALUE")

14. This calculates the average order value for all orders where delivered quantity > ordered quantity
AVG(
  CASE
    WHEN "_APX_WDCRP_CASES"."ORDERED_QUANTITY" < "_APX_WDCRP_CASES"."DELIVERED_QUANTITY" THEN "_APX_WDCRP_CASES"."ORDER_VALUE"
    ELSE 0.0
  END
)

15. If you want average order value of only over-delivered orders
AVG(
  CASE
    WHEN "_APX_WDCRP_CASES"."ORDERED_QUANTITY" > "_APX_WDCRP_CASES"."DELIVERED_QUANTITY" THEN "_APX_WDCRP_CASES"."ORDER_VALUE"
    ELSE 0.0
  END
)

16.  Lost Value Due to Partial Fulfillment
SUM(
  CASE 
    WHEN "_APX_WDCRP_CASES"."DELIVERED_QUANTITY" < "_APX_WDCRP_CASES"."ORDERED_QUANTITY"
    THEN ("_APX_WDCRP_CASES"."ORDERED_QUANTITY" - "_APX_WDCRP_CASES"."DELIVERED_QUANTITY") * "_APX_WDCRP_CASES"."UNIT_PRICE"
    ELSE 0 
  END
)
It calculates the total monetary value of under-delivered quantities.

In other words:

For every order where less was delivered than ordered,

It computes:
→ (Ordered – Delivered) × Unit Price
→ = the estimated value of the quantity not delivered

Then it sums up these values across all such cases.


17. 
SUM(
  CASE 
    WHEN "_APX_WDCRP_CASES"."DELIVERED_QUANTITY" < "_APX_WDCRP_CASES"."ORDERED_QUANTITY" 
    THEN "_APX_WDCRP_CASES"."ORDERED_QUANTITY" - "_APX_WDCRP_CASES"."DELIVERED_QUANTITY"
    ELSE 0 
  END
)

18. Ordered Qty:
  SUM("_APX_WDCRP_CASES"."ORDERED_QUANTITY")
  
19.  Delivered Qty:
  SUM("_APX_WDCRP_CASES"."DELIVERED_QUANTITY")

20. Not Delivered Qty:
SUM(
  "_APX_WDCRP_CASES"."ORDERED_QUANTITY" - "_APX_WDCRP_CASES"."DELIVERED_QUANTITY"
)

