1. On-time Delivery:

AVG(
  CASE 
    WHEN "_APX_WDCRP_CASES"."PROMISED_DATE" >= "_APX_WDCRP_CASES"."DELIVERED_DATE" 
    THEN 1.0 
    ELSE 0.0 
  END
)

2. Early Delivery:
AVG(
  CASE 
    WHEN "_APX_WDCRP_CASES"."DELIVERED_DATE" < "_APX_WDCRP_CASES"."PROMISED_DATE" 
    THEN 1.0 
    ELSE 0.0 
  END
)

3. Late Delivery :
AVG(
  CASE 
    WHEN "_APX_WDCRP_CASES"."DELIVERED_DATE" > "_APX_WDCRP_CASES"."PROMISED_DATE" 
    THEN 1.0 
    ELSE 0.0 
  END
)
  
4.  Rework Rate :
SUM(CASE WHEN PU_COUNT("_APX_WDCRP_CASES","_APX_WDCRP_ACTIVITIES"."ACTIVITY_EN","_APX_WDCRP_ACTIVITIES"."ACTIVITY_EN" 
IN (<%=reworkActivities%>)) > 1 THEN 1.0 ELSE 0.0 END) / COUNT_TABLE("_APX_WDCRP_CASES")

5. Late Delivery fee :
SUM(
  CASE 
    WHEN "_APX_WDCRP_CASES"."DELIVERED_DATE" > "_APX_WDCRP_CASES"."PROMISED_DATE" 
    THEN "_APX_WDCRP_CASES"."DELIVERED_QUANTITY" * 0.75 
    ELSE 0 
  END
)

6.  Deadline conformance:
AVG(
  CASE
    WHEN "_APX_WDCRP_CASES"."DELIVERED_DATE" <= "_APX_WDCRP_CASES"."PROMISED_DATE" THEN 1.0
    ELSE 0.0
  END
)

7. Volume Conformance :
AVG(
  CASE
    WHEN "_APX_WDCRP_CASES"."ORDERED_QUANTITY" <= "_APX_WDCRP_CASES"."DELIVERED_QUANTITY" THEN 1.0
    ELSE 0.0
  END
)

8. Loss Ratio :
(
  AVG(
    CASE 
      WHEN "_APX_WDCRP_CASES"."DELIVERED_DATE" > "_APX_WDCRP_CASES"."PROMISED_DATE"
      THEN "_APX_WDCRP_CASES"."DELIVERED_QUANTITY" * 0.75
      ELSE 0
    END
  )
  /
  AVG("_APX_WDCRP_CASES"."ORDER_VALUE")
)

9. 
